version: 0.2

phases:
  install:
    runtime-versions:
       golang: 1.x
  pre_build:
    commands:
      - go get
  build:
    commands:
      - sh build.sh
  post_build:
    commands:
      - aws lambda update-function-code --function-name auth --zip-file fileb://auth.zip
      - aws lambda publish-version --function-name auth > res.json
      - export VERSION=$(jq -r '.Version' res.json)
      - aws lambda update-alias --function-name auth --function-version $VERSION --name dev
